os: osx

cache:
  directories:
    - $HOME/.ccache

install:
  - brew update
  - brew install mono
  - brew install ccache
  - Stuff/stuff install Stuff

before_script:
  - export CC="ccache clang"
  - export CXX="ccache clang++"

script:
  - Stuff/uno --trace doctor
  - Stuff/uno --trace test -tnative --timeout=30 Source
